using System.Text.Json;
using PharmaBack.WebApi.Data;
using PharmaBack.WebApi.Models;

namespace PharmaBack.WebApi.Seeding;

public static class Seeder
{
    public static async Task SeedAsync(PharmaDbContext db, IWebHostEnvironment env)
    {
        var products = new List<Product>
        {
            new()
            {
                Barcode = "0000000",
                Brand = "Biogesic",
                Generic = "Paracetamol",
                RetailPrice = 26.77M,
                WholesalePrice = 5.38M,
                Quantity = 200,
                Location = "Shelf 5",
                MinStock = 11,

                IsDeleted = false,
                Category = "Analgesic",
                Formulation = "Tablet",
                Company = "Pharma Inc",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000001",
                Brand = "Alaxan FR",
                Generic = "Ibuprofen",
                RetailPrice = 32.89M,
                WholesalePrice = 22.09M,
                Quantity = 110,

                Location = "Shelf 1",
                MinStock = 10,

                IsDeleted = false,
                Category = "Antihistamine",
                Formulation = "Capsule",
                Company = "MediHealth",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "0000002",
                Brand = "Neozep",
                Generic = "Phenylephrine",
                RetailPrice = 22.46M,
                WholesalePrice = 14.53M,
                Quantity = 13,

                Location = "Shelf 1",
                MinStock = 6,

                IsDeleted = false,
                Category = "Cough",
                Formulation = "Syrup",
                Company = "WellnessCorp",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000003",
                Brand = "Solmux",
                Generic = "Loratadine",
                RetailPrice = 42.24M,
                WholesalePrice = 21.07M,
                Quantity = 128,

                Location = "Shelf 2",
                MinStock = 15,

                IsDeleted = false,
                Category = "Cold",
                Formulation = "Suspension",
                Company = "BioPharm",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "0000004",
                Brand = "Diatabs",
                Generic = "Cetirizine",
                RetailPrice = 24.48M,
                WholesalePrice = 19.43M,
                Quantity = 111,

                Location = "Shelf 3",
                MinStock = 18,

                IsDeleted = false,
                Category = "Digestive",
                Formulation = "Lozenge",
                Company = "CureAll",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000005",
                Brand = "Tempra",
                Generic = "Diphenhydramine",
                RetailPrice = 27.05M,
                WholesalePrice = 25.44M,
                Quantity = 164,

                Location = "Shelf 1",
                MinStock = 16,

                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Drop",
                Company = "Pharma Inc",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "0000006",
                Brand = "Tuseran Forte",
                Generic = "Ambroxol",
                RetailPrice = 32.14M,
                WholesalePrice = 28.44M,
                Quantity = 159,

                Location = "Shelf 1",
                MinStock = 10,

                IsDeleted = false,
                Category = "Analgesic",
                Formulation = "Inhaler",
                Company = "MediHealth",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000007",
                Brand = "Bioflu",
                Generic = "Loperamide",
                RetailPrice = 26.91M,
                WholesalePrice = 29.73M,
                Quantity = 108,

                Location = "Shelf 2",
                MinStock = 16,

                IsDeleted = false,
                Category = "Antihistamine",
                Formulation = "Tablet",
                Company = "WellnessCorp",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "0000008",
                Brand = "Decolgen",
                Generic = "Ascorbic Acid",
                RetailPrice = 16.68M,
                WholesalePrice = 8.29M,
                Quantity = 161,

                Location = "Shelf 1",
                MinStock = 7,

                IsDeleted = false,
                Category = "Cough",
                Formulation = "Capsule",
                Company = "BioPharm",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000009",
                Brand = "Benadryl",
                Generic = "Aluminum Hydroxide",
                RetailPrice = 13.67M,
                WholesalePrice = 15.66M,
                Quantity = 19,

                Location = "Shelf 2",
                MinStock = 8,

                IsDeleted = false,
                Category = "Cold",
                Formulation = "Syrup",
                Company = "CureAll",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "0000010",
                Brand = "Claritin",
                Generic = "Paracetamol",
                RetailPrice = 18.1M,
                WholesalePrice = 10.0M,
                Quantity = 27,

                Location = "Shelf 4",
                MinStock = 14,

                IsDeleted = false,
                Category = "Digestive",
                Formulation = "Suspension",
                Company = "Pharma Inc",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000011",
                Brand = "Mucinex",
                Generic = "Ibuprofen",
                RetailPrice = 22.46M,
                WholesalePrice = 6.06M,
                Quantity = 96,

                Location = "Shelf 3",
                MinStock = 6,

                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Lozenge",
                Company = "MediHealth",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "0000012",
                Brand = "Zyrtec",
                Generic = "Phenylephrine",
                RetailPrice = 36.52M,
                WholesalePrice = 9.17M,
                Quantity = 59,

                Location = "Shelf 2",
                MinStock = 7,

                IsDeleted = false,
                Category = "Analgesic",
                Formulation = "Drop",
                Company = "WellnessCorp",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000013",
                Brand = "Cetirizine",
                Generic = "Loratadine",
                RetailPrice = 42.6M,
                WholesalePrice = 29.7M,
                Quantity = 71,

                Location = "Shelf 4",
                MinStock = 9,

                IsDeleted = false,
                Category = "Antihistamine",
                Formulation = "Inhaler",
                Company = "BioPharm",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "0000014",
                Brand = "Ibuprofen",
                Generic = "Cetirizine",
                RetailPrice = 26.64M,
                WholesalePrice = 23.63M,
                Quantity = 140,

                Location = "Shelf 1",
                MinStock = 10,

                IsDeleted = false,
                Category = "Cough",
                Formulation = "Tablet",
                Company = "CureAll",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000015",
                Brand = "Paracetamol",
                Generic = "Diphenhydramine",
                RetailPrice = 37.33M,
                WholesalePrice = 19.81M,
                Quantity = 96,

                Location = "Shelf 4",
                MinStock = 19,

                IsDeleted = false,
                Category = "Cold",
                Formulation = "Capsule",
                Company = "Pharma Inc",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "0000016",
                Brand = "Ambroxol",
                Generic = "Ambroxol",
                RetailPrice = 27.97M,
                WholesalePrice = 28.13M,
                Quantity = 24,

                Location = "Shelf 4",
                MinStock = 9,

                IsDeleted = false,
                Category = "Digestive",
                Formulation = "Syrup",
                Company = "MediHealth",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000017",
                Brand = "Loperamide",
                Generic = "Loperamide",
                RetailPrice = 49.25M,
                WholesalePrice = 19.82M,
                Quantity = 49,

                Location = "Shelf 5",
                MinStock = 15,

                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Suspension",
                Company = "WellnessCorp",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "0000018",
                Brand = "Antacid",
                Generic = "Ascorbic Acid",
                RetailPrice = 49.26M,
                WholesalePrice = 19.09M,
                Quantity = 66,

                Location = "Shelf 1",
                MinStock = 14,

                IsDeleted = false,
                Category = "Analgesic",
                Formulation = "Lozenge",
                Company = "BioPharm",
                Type = "OTC",
            },
            new()
            {
                Barcode = "0000019",
                Brand = "Vitamin C",
                Generic = "Aluminum Hydroxide",
                RetailPrice = 21.38M,
                WholesalePrice = 15.44M,
                Quantity = 35,

                Location = "Shelf 5",
                MinStock = 19,

                IsDeleted = false,
                Category = "Antihistamine",
                Formulation = "Drop",
                Company = "CureAll",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1000",
                Brand = "Cefalexin",
                Generic = "Cefalexin Monohydrate",
                RetailPrice = 34.75M,
                WholesalePrice = 20.50M,
                Quantity = 100,
                Location = "Shelf A1",
                MinStock = 10,
                IsDeleted = false,
                Category = "Antibiotic",
                Formulation = "Capsule",
                Company = "GenPharm",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1001",
                Brand = "Amoxicillin",
                Generic = "Amoxicillin Trihydrate",
                RetailPrice = 28.99M,
                WholesalePrice = 18.50M,
                Quantity = 120,
                Location = "Shelf A2",
                MinStock = 15,
                IsDeleted = false,
                Category = "Antibiotic",
                Formulation = "Tablet",
                Company = "HealthRx",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1002",
                Brand = "Metformin",
                Generic = "Metformin HCl",
                RetailPrice = 22.80M,
                WholesalePrice = 14.00M,
                Quantity = 150,
                Location = "Shelf B1",
                MinStock = 20,
                IsDeleted = false,
                Category = "Diabetes",
                Formulation = "Tablet",
                Company = "WellPharma",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1003",
                Brand = "Loperex",
                Generic = "Loperamide",
                RetailPrice = 17.30M,
                WholesalePrice = 10.00M,
                Quantity = 200,
                Location = "Shelf C1",
                MinStock = 12,
                IsDeleted = false,
                Category = "Digestive",
                Formulation = "Tablet",
                Company = "DigestiveCare",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1004",
                Brand = "ZincPlus",
                Generic = "Zinc Sulfate",
                RetailPrice = 18.25M,
                WholesalePrice = 11.50M,
                Quantity = 130,
                Location = "Shelf D2",
                MinStock = 10,
                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Drop",
                Company = "NutraHeal",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1005",
                Brand = "Omeprazole",
                Generic = "Omeprazole",
                RetailPrice = 24.99M,
                WholesalePrice = 16.00M,
                Quantity = 80,
                Location = "Shelf E3",
                MinStock = 8,
                IsDeleted = false,
                Category = "Gastrointestinal",
                Formulation = "Capsule",
                Company = "GastroCare",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1006",
                Brand = "Ibuprocap",
                Generic = "Ibuprofen",
                RetailPrice = 31.75M,
                WholesalePrice = 20.00M,
                Quantity = 60,
                Location = "Shelf F1",
                MinStock = 6,
                IsDeleted = false,
                Category = "Analgesic",
                Formulation = "Tablet",
                Company = "PainAway",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1007",
                Brand = "Vitafizz",
                Generic = "Multivitamins",
                RetailPrice = 38.20M,
                WholesalePrice = 22.75M,
                Quantity = 140,
                Location = "Shelf G2",
                MinStock = 14,
                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Tablet",
                Company = "HealthPlus",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1008",
                Brand = "Mucolyte",
                Generic = "Ambroxol",
                RetailPrice = 19.50M,
                WholesalePrice = 13.00M,
                Quantity = 90,
                Location = "Shelf H3",
                MinStock = 9,
                IsDeleted = false,
                Category = "Cough",
                Formulation = "Syrup",
                Company = "RespiraMed",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1009",
                Brand = "CoughClear",
                Generic = "Guaifenesin",
                RetailPrice = 25.60M,
                WholesalePrice = 17.20M,
                Quantity = 85,
                Location = "Shelf J1",
                MinStock = 8,
                IsDeleted = false,
                Category = "Cough",
                Formulation = "Syrup",
                Company = "SanaWell",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1010",
                Brand = "Parazorb",
                Generic = "Mebendazole",
                RetailPrice = 16.30M,
                WholesalePrice = 10.80M,
                Quantity = 115,
                Location = "Shelf K4",
                MinStock = 12,
                IsDeleted = false,
                Category = "Antiparasitic",
                Formulation = "Tablet",
                Company = "SafeMeds",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1011",
                Brand = "Antamin",
                Generic = "Diphenhydramine",
                RetailPrice = 18.00M,
                WholesalePrice = 12.40M,
                Quantity = 70,
                Location = "Shelf L2",
                MinStock = 7,
                IsDeleted = false,
                Category = "Antihistamine",
                Formulation = "Tablet",
                Company = "AllerCare",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1012",
                Brand = "Feronix",
                Generic = "Ferrous Sulfate",
                RetailPrice = 21.90M,
                WholesalePrice = 14.25M,
                Quantity = 95,
                Location = "Shelf M3",
                MinStock = 10,
                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Capsule",
                Company = "NutraGen",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1013",
                Brand = "Chlortan",
                Generic = "Chlorpheniramine",
                RetailPrice = 14.40M,
                WholesalePrice = 9.20M,
                Quantity = 75,
                Location = "Shelf N5",
                MinStock = 8,
                IsDeleted = false,
                Category = "Antihistamine",
                Formulation = "Syrup",
                Company = "ReliefPharm",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1014",
                Brand = "Allerkid",
                Generic = "Cetirizine",
                RetailPrice = 23.30M,
                WholesalePrice = 15.90M,
                Quantity = 105,
                Location = "Shelf O6",
                MinStock = 11,
                IsDeleted = false,
                Category = "Antihistamine",
                Formulation = "Drop",
                Company = "CarePlus",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1015",
                Brand = "Dextroclear",
                Generic = "Dextromethorphan",
                RetailPrice = 20.40M,
                WholesalePrice = 14.10M,
                Quantity = 88,
                Location = "Shelf P3",
                MinStock = 9,
                IsDeleted = false,
                Category = "Cough",
                Formulation = "Suspension",
                Company = "CoughGo",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1016",
                Brand = "GlucoRx",
                Generic = "Glibenclamide",
                RetailPrice = 32.25M,
                WholesalePrice = 21.80M,
                Quantity = 65,
                Location = "Shelf Q2",
                MinStock = 10,
                IsDeleted = false,
                Category = "Diabetes",
                Formulation = "Tablet",
                Company = "LifeMeds",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1017",
                Brand = "NeuroB",
                Generic = "Vitamin B Complex",
                RetailPrice = 26.10M,
                WholesalePrice = 17.50M,
                Quantity = 140,
                Location = "Shelf R1",
                MinStock = 14,
                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Tablet",
                Company = "NeuroCare",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1018",
                Brand = "IronMax",
                Generic = "Iron + Folic Acid",
                RetailPrice = 29.90M,
                WholesalePrice = 19.60M,
                Quantity = 92,
                Location = "Shelf S3",
                MinStock = 11,
                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Capsule",
                Company = "VitalCore",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1019",
                Brand = "CalPlus D",
                Generic = "Calcium + Vitamin D3",
                RetailPrice = 35.80M,
                WholesalePrice = 23.40M,
                Quantity = 98,
                Location = "Shelf T4",
                MinStock = 13,
                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Tablet",
                Company = "BoneWell",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1020",
                Brand = "DoloMed",
                Generic = "Tramadol",
                RetailPrice = 41.20M,
                WholesalePrice = 29.50M,
                Quantity = 90,
                Location = "Shelf U1",
                MinStock = 10,
                IsDeleted = false,
                Category = "Analgesic",
                Formulation = "Tablet",
                Company = "PainRelief Inc.",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1021",
                Brand = "Respivent",
                Generic = "Salbutamol",
                RetailPrice = 33.75M,
                WholesalePrice = 22.10M,
                Quantity = 130,
                Location = "Shelf V2",
                MinStock = 12,
                IsDeleted = false,
                Category = "Respiratory",
                Formulation = "Inhaler",
                Company = "AirHealth",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1022",
                Brand = "Meforin",
                Generic = "Mefenamic Acid",
                RetailPrice = 25.20M,
                WholesalePrice = 16.00M,
                Quantity = 75,
                Location = "Shelf W3",
                MinStock = 8,
                IsDeleted = false,
                Category = "Analgesic",
                Formulation = "Tablet",
                Company = "Relievia",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1023",
                Brand = "Ultragel",
                Generic = "Aluminum Hydroxide",
                RetailPrice = 18.50M,
                WholesalePrice = 12.00M,
                Quantity = 100,
                Location = "Shelf X1",
                MinStock = 10,
                IsDeleted = false,
                Category = "Digestive",
                Formulation = "Suspension",
                Company = "AcidRelief",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1024",
                Brand = "Myra-E",
                Generic = "Vitamin E",
                RetailPrice = 31.90M,
                WholesalePrice = 21.50M,
                Quantity = 150,
                Location = "Shelf Y1",
                MinStock = 15,
                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Capsule",
                Company = "NutriLife",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1025",
                Brand = "Diacare",
                Generic = "Gliclazide",
                RetailPrice = 28.10M,
                WholesalePrice = 19.40M,
                Quantity = 88,
                Location = "Shelf Z1",
                MinStock = 9,
                IsDeleted = false,
                Category = "Diabetes",
                Formulation = "Tablet",
                Company = "GlucoHealth",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1026",
                Brand = "Immunix",
                Generic = "Zinc + Vitamin C",
                RetailPrice = 35.00M,
                WholesalePrice = 24.00M,
                Quantity = 95,
                Location = "Shelf AA2",
                MinStock = 10,
                IsDeleted = false,
                Category = "Supplement",
                Formulation = "Tablet",
                Company = "WellShield",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1027",
                Brand = "AntiFever",
                Generic = "Paracetamol",
                RetailPrice = 14.99M,
                WholesalePrice = 8.00M,
                Quantity = 120,
                Location = "Shelf BB2",
                MinStock = 10,
                IsDeleted = false,
                Category = "Antipyretic",
                Formulation = "Tablet",
                Company = "ThermoPharm",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1028",
                Brand = "Zymotol",
                Generic = "Simethicone",
                RetailPrice = 23.75M,
                WholesalePrice = 15.60M,
                Quantity = 60,
                Location = "Shelf CC1",
                MinStock = 6,
                IsDeleted = false,
                Category = "Digestive",
                Formulation = "Drop",
                Company = "GasRelief Inc.",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1029",
                Brand = "FlowAir",
                Generic = "Montelukast",
                RetailPrice = 37.50M,
                WholesalePrice = 25.00M,
                Quantity = 85,
                Location = "Shelf DD2",
                MinStock = 9,
                IsDeleted = false,
                Category = "Respiratory",
                Formulation = "Tablet",
                Company = "BreatheEase",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1030",
                Brand = "Neurogen-E",
                Generic = "Vitamin B1+B6+B12",
                RetailPrice = 29.95M,
                WholesalePrice = 18.90M,
                Quantity = 110,
                Location = "Shelf EE3",
                MinStock = 11,
                IsDeleted = false,
                Category = "Neurological",
                Formulation = "Tablet",
                Company = "NeuroCare",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1031",
                Brand = "Systolex",
                Generic = "Amlodipine",
                RetailPrice = 26.99M,
                WholesalePrice = 17.20M,
                Quantity = 98,
                Location = "Shelf FF1",
                MinStock = 10,
                IsDeleted = false,
                Category = "Cardiovascular",
                Formulation = "Tablet",
                Company = "HeartMed",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1032",
                Brand = "Relent",
                Generic = "Cetirizine + Phenylephrine",
                RetailPrice = 24.30M,
                WholesalePrice = 15.10M,
                Quantity = 72,
                Location = "Shelf GG2",
                MinStock = 8,
                IsDeleted = false,
                Category = "Allergy",
                Formulation = "Syrup",
                Company = "AllergyCare",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1033",
                Brand = "Tensionol",
                Generic = "Losartan",
                RetailPrice = 30.60M,
                WholesalePrice = 19.90M,
                Quantity = 105,
                Location = "Shelf HH2",
                MinStock = 12,
                IsDeleted = false,
                Category = "Cardiovascular",
                Formulation = "Tablet",
                Company = "BPHealth",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1034",
                Brand = "Hydramed",
                Generic = "Oral Rehydration Salts",
                RetailPrice = 10.50M,
                WholesalePrice = 6.75M,
                Quantity = 160,
                Location = "Shelf II2",
                MinStock = 15,
                IsDeleted = false,
                Category = "Hydration",
                Formulation = "Powder",
                Company = "ElectrolyteCo",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1035",
                Brand = "Antacid Plus",
                Generic = "Magaldrate + Simethicone",
                RetailPrice = 20.40M,
                WholesalePrice = 13.70M,
                Quantity = 91,
                Location = "Shelf JJ1",
                MinStock = 10,
                IsDeleted = false,
                Category = "Digestive",
                Formulation = "Suspension",
                Company = "AcidBalance",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1036",
                Brand = "ClearSkin",
                Generic = "Isotretinoin",
                RetailPrice = 55.00M,
                WholesalePrice = 40.00M,
                Quantity = 45,
                Location = "Shelf KK3",
                MinStock = 5,
                IsDeleted = false,
                Category = "Dermatology",
                Formulation = "Capsule",
                Company = "SkinRx",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1037",
                Brand = "EyeMoist",
                Generic = "Carboxymethylcellulose",
                RetailPrice = 15.90M,
                WholesalePrice = 10.50M,
                Quantity = 70,
                Location = "Shelf LL1",
                MinStock = 7,
                IsDeleted = false,
                Category = "Ophthalmology",
                Formulation = "Drop",
                Company = "VisionCare",
                Type = "OTC",
            },
            new()
            {
                Barcode = "NEW1038",
                Brand = "LaxaSoft",
                Generic = "Lactulose",
                RetailPrice = 22.40M,
                WholesalePrice = 14.70M,
                Quantity = 100,
                Location = "Shelf MM2",
                MinStock = 10,
                IsDeleted = false,
                Category = "Digestive",
                Formulation = "Syrup",
                Company = "BowelHealth",
                Type = "Prescription",
            },
            new()
            {
                Barcode = "NEW1039",
                Brand = "Gavisoothe",
                Generic = "Calcium Carbonate + Magnesium Hydroxide",
                RetailPrice = 18.99M,
                WholesalePrice = 13.25M,
                Quantity = 112,
                Location = "Shelf NN1",
                MinStock = 9,
                IsDeleted = false,
                Category = "Antacid",
                Formulation = "Chewable",
                Company = "StomachEase",
                Type = "OTC",
            },
        };

        db.Products.AddRange(products);
        await db.SaveChangesAsync();
    }
}
